PUT http://localhost:3001/api/blogs/6
Content-Type: application/json

{
    "likes": 2
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "author": "Maukumau",
    "url": "www.kissamau.fi",
    "title": "Maaaauu maau"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Kissa miu",
    "username": "kiskis"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Miumiu",
    "password": "salainen"
}

###

PUT http://localhost:3001/api/users/Miumiu
Content-Type: application/json

{
    "username": "Maukumau"
}