PUT http://localhost:3001/api/blogs/6
Content-Type: application/json

{
    "likes": 2
}

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imtpc3NhQG1hdS5jb20iLCJpZCI6NSwiaWF0IjoxNjM5NzQwMjgxfQ.eaLv-q9Ol5m5m9ylTowuf2WOQIRc9kA0chfY2qqZmdo

{
    "author": "Maukumau",
    "url": "www.kissamau.fi",
    "title": "Testikirja 1"
}

###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "name": "Mirri mau",
    "username": "pspsps@psps.com"
}

###

POST http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "kissa@mau.com",
    "password": "salainen"
}

###

PUT http://localhost:3001/api/users/Miumiu
Content-Type: application/json

{
    "username": "Maukumau"
}

###

DELETE  http://localhost:3001/api/users/4

###
DELETE  http://localhost:3001/api/blogs/5